GA:
  crossover: 0.8
  generation: (50k - pop)/pop
  mutation_rate: 0.02
  pop: 500
  tournament_k: 5
algos:
- GA
experiment:
  code_version: ''
  exp_id: exp_001
  instances: 5
  n_list:
  - 30
  run_csv: GA_pop_3_run.csv
  runs_per_instance: 3
  scale: 100.0
  trace_csv: GA_pop_3_trace.csv
