experiment:
  exp_id: exp_kp_001
  n_items_list: [100]
  instances: 5
  runs_per_instance: 3


  weight_low: 1
  weight_high: 50
  value_low: 1
  value_high: 100
  capacity_ratio: 0.5        # capacity = ratio * sum(weights)

  penalty_lambda: 1000.0     
  feasible_only: true        # if true, repair solutions to feasibility

  run_csv: knapsack_SA_step_1_run.csv
  trace_csv: knapsack_SA_step_1_trace.csv
  code_version: ""

# algos: [SA_KP, GA_KP, HC_KP, TLBO_KP, ABC_KP]
algos: [SA_KP]


# SA base
# SA_KP:
#   T0: 100.0
#   alpha: 0.99
#   Tmin: 0.001
#   max_iter: 50000
#   trace_every: 200
#   step_per_temp: 2000

# SA T01
# SA_KP:
#   T0: 10.0
#   alpha: 0.99
#   Tmin: 0.001
#   max_iter: 50000
#   trace_every: 200
#   step_per_temp: 2000

# SA T02
# SA_KP:
#   T0: 500.0
#   alpha: 0.99
#   Tmin: 0.001
#   max_iter: 50000
#   trace_every: 200
#   step_per_temp: 2000

# SA T03
# SA_KP:
#   T0: 1000.0
#   alpha: 0.99
#   Tmin: 0.001
#   max_iter: 50000
#   trace_every: 200
#   step_per_temp: 2000

# SA step 1
SA_KP:
  T0: 100.0
  alpha: 0.99
  Tmin: 0.001
  max_iter: 50000
  trace_every: 200
  steps_per_temp: 500

# SA step 2
# SA_KP:
#   T0: 100.0
#   alpha: 0.99   
#   Tmin: 0.001
#   max_iter: 50000
#   trace_every: 200
#   steps_per_temp: 1000

# SA step 3
# SA_KP:
#   T0: 100.0
#   alpha: 0.99
#   Tmin: 0.001
#   max_iter: 50000
#   trace_every: 200
#   steps_per_temp: 4000

# GA base
# GA_KP:
#   population_size: 100
#   generations: (50000 - population_size) / population_size
#   crossover_rate: 0.8
#   mutation_rate: 0.02
#   tournament_k: 5
#   trace_every: 10

# GA pop 1
# GA_KP:
#   population_size: 20
#   generations: (50000 - population_size) / population_size
#   crossover_rate: 0.8
#   mutation_rate: 0.02
#   tournament_k: 5
#   trace_every: 10

# GA pop 2
# GA_KP:
#   population_size: 50
#   generations: (50000 - population_size) / population_size
#   crossover_rate: 0.8
#   mutation_rate: 0.02
#   tournament_k: 5
#   trace_every: 10

# GA pop 3
# GA_KP:
#   population_size: 500
#   generations: (50000 - population_size) / population_size
#   crossover_rate: 0.8
#   mutation_rate: 0.02
#   tournament_k: 5
#   trace_every: 10

# GA cross 1
# GA_KP:
#   population_size: 100
#   generations: (50000 - population_size) / population_size
#   crossover_rate: 0.6
#   mutation_rate: 0.02
#   tournament_k: 5
#   trace_every: 10

# GA cross 2
# GA_KP:
#   population_size: 100
#   generations: (50000 - population_size) / population_size
#   crossover_rate: 0.7
#   mutation_rate: 0.02
#   tournament_k: 5
#   trace_every: 10

# GA cross 3
# GA_KP:
#   population_size: 100
#   generations: (50000 - population_size) / population_size
#   crossover_rate: 0.9
#   mutation_rate: 0.02
#   tournament_k: 5
#   trace_every: 10

# GA mut 1
# GA_KP:
#   population_size: 100
#   generations: (50000 - population_size) / population_size
#   crossover_rate: 0.8
#   mutation_rate: 0.01
#   tournament_k: 5
#   trace_every: 10

# GA mut 2
# GA_KP:
#   population_size: 100
#   generations: (50000 - population_size) / population_size
#   crossover_rate: 0.8
#   mutation_rate: 0.05
#   tournament_k: 5
#   trace_every: 10

# GA mut 3
# GA_KP:
#   population_size: 100
#   generations: (50000 - population_size) / population_size
#   crossover_rate: 0.8
#   mutation_rate: 0.1
#   tournament_k: 5
#   trace_every: 10

# GA tour 1
# GA_KP:
#   population_size: 100
#   generations: (50000 - population_size) / population_size
#   crossover_rate: 0.8
#   mutation_rate: 0.02
#   tournament_k: 3
#   trace_every: 10

# GA tour 2
# GA_KP:
#   population_size: 100
#   generations: (50000 - population_size) / population_size
#   crossover_rate: 0.8
#   mutation_rate: 0.02
#   tournament_k: 10
#   trace_every: 10

# GA tour 3
# GA_KP:
#   population_size: 100
#   generations: (50000 - population_size) / population_size
#   crossover_rate: 0.8
#   mutation_rate: 0.02
#   tournament_k: 20
#   trace_every: 10 
  
# HC first
# HC_KP:
#   max_iter: 50000
#   mode: first                # first | best
#   trace_every: 200
#   flip_k: 1

# HC best
# HC_KP:
#   max_iter: 50000
#   mode: best                 # first | best
#   trace_every: 200
#   flip_k: 1

# TLBO base
# TLBO_KP:
#   pop_size: 50
#   move_frac_max: 0.4
#   iters: 500
#   trace_every: 10

# TLBO pop 1
# TLBO_KP:
#   pop_size: 30
#   move_frac_max: 0.4
#   iters: 500
#   trace_every: 10

# TLBO pop 2
# TLBO_KP:
#   pop_size: 80
#   move_frac_max: 0.4
#   iters: 500
#   trace_every: 10

# TLBO pop 3
# TLBO_KP:
#   pop_size: 120
#   move_frac_max: 0.4
#   iters: 500
#   trace_every: 10

# TLBO move frac 1
# TLBO_KP:
#   pop_size: 50
#   move_frac_max: 0.2
#   iters: 500
#   trace_every: 10

# TLBO move frac 2
# TLBO_KP:
#   pop_size: 50
#   move_frac_max: 0.6
#   iters: 500
#   trace_every: 10

# TLBO move frac 3
# TLBO_KP:
#   pop_size: 50
#   move_frac_max: 0.8
#   iters: 500
#   trace_every: 10

# ABC base
# ABC_KP:
#   sn: 50                   # number of food sources
#   iters: 500
#   limit: 25
#   trace_every: 10

# # ABC sn 1
# ABC_KP:
#   sn: 10
#   iters: 500
#   limit: 25
#   trace_every: 10

# ABC sn 2
# ABC_KP:
#   sn: 100
#   iters: 500
#   limit: 25 
#   trace_every: 10

# ABC sn 3
# ABC_KP:
#   sn: 500
#   iters: 500
#   limit: 25
#   trace_every: 10
  
# ABC limit 1
# ABC_KP:
#   sn: 50
#   iters: 500
#   limit: 10
#   trace_every: 10

# ABC limit 2
# ABC_KP:
#   sn: 50
#   iters: 500
#   limit: 50
#   trace_every: 10

# ABC limit 3
ABC_KP:
  sn: 50
  iters: 500
  limit: 100
  trace_every: 10
  